apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-boot-dep
  annotations:
    # ArgoCD 전용 어노테이션 (선택 사항)
    # sync-wave 없으면 DB 연결 실패 후 재시작으로 결국 성공하지만,
    # 순서를 보장하면 처음부터 깔끔하게 배포됨
    argocd.argoproj.io/sync-wave: "3"  # 배포 순서: 3 (MariaDB 준비 후)
spec:
  selector:
    matchLabels:
      app: bootdep
  # replicas: 3
  replicas: 1
  template:
    metadata:
      labels:
        app: bootdep
    spec:
      containers:
      - name: boot-container
        image: ys0915/argo_boot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
        # MariaDB 연결을 위한 환경변수 설정
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://argo-mariadb-ser:3310/calcdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root1234"
        # Health Check - Spring Boot가 정상 실행되는지 확인
        readinessProbe:
          httpGet:
            path: /health
            port: 7777
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 7777
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
